"""third commit

Revision ID: 999c48b1cb87
Revises: 8ba89d7939ed
Create Date: 2022-03-18 16:38:53.858423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999c48b1cb87'
down_revision = '8ba89d7939ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
